version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  habits:
    build: ./lambdas/habits
    ports:
      - "8001:8080"
    env_file:
      - .env
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

  checkin:
    build: ./lambdas/checkin
    ports:
      - "8002:8080"
    env_file:
      - .env
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

  analytics:
    build: ./lambdas/analytics
    ports:
      - "8003:8080"
    env_file:
      - .env
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

  health:
    build: ./lambdas/health
    ports:
      - "8004:8080"
    env_file:
      - .env
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
